name: Build, Test and Deploy

on: push

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    container:
      image: elixir:1.9.1-slim
      env:
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOSTNAME: postgres
        POSTGRES_PORT: 5432

    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run Tests
        run: mix test
  deploy:
    name: deploy
    needs: job1
    - name: Login to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        args: container:login
      uses: actions/heroku@9b6266f8ca2b26bc846af2547b2b11ad8a696223
    - name: Push to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        args: container:push -a still-atoll-56227 web
      uses: actions/heroku@9b6266f8ca2b26bc846af2547b2b11ad8a696223
    - name: Push to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        args: container:release -a still-atoll-56227 web
      uses: actions/heroku@9b6266f8ca2b26bc846af2547b2b11ad8a696223
