name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Login to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} 
        args: container:login
      uses: actions/heroku@9b6266f8ca2b26bc846af2547b2b11ad8a696223
  


